---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-scaling-example-com-v1-podscaler
  failurePolicy: Fail
  name: mpodscaler-v1.kb.io
  rules:
  - apiGroups:
    - scaling.example.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podscalers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-scaling-example-com-v1-podscaler
  failurePolicy: Fail
  name: vpodscaler-v1.kb.io
  rules:
  - apiGroups:
    - scaling.example.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podscalers
  sideEffects: None
