# permissions for end users to edit podscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-scaler
    app.kubernetes.io/managed-by: kustomize
  name: podscaler-editor-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers/status
  verbs:
  - get
