# permissions for end users to view podscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-scaler
    app.kubernetes.io/managed-by: kustomize
  name: podscaler-viewer-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers/status
  verbs:
  - get
