apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.example.com
  resources:
  - podscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""  # 空文字列は core API グループを示す
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
